Feature helm test for e2e (#38)
* Update datasource-checker.json

* Add selenium-grid chart with e2e tests

* Fix typo in the app.yaml of selenium

* Fix url values to be independent of the namespace

* Add ArgoCD waves to many deployments

* Test another values for the ArgoCD waves

* Add selenium-grid chart with e2e tests

* Fix typo in the app.yaml of selenium

* Fix url values to be independent of the namespace

* Add ArgoCD waves to many deployments

* Test another values for the ArgoCD waves

* Fix values

* Fix value for testing grafana

* Change image pull policy to always

* Update CI with a way of knowing that apps are healthy

* Change values to a working state for the helm test

* Add e2e pod hardcoded for testing

* Fix typo in the ci

* Fix typo in ci

* Add branch to deploy the pod in the right namespace

* Delete helm test and create chart for e2e

* Update ci to launch e2e test helm chart

* Fix namespace in ci

* Change pod to job and wait for his completion in the ci

* Change apiversion in the job

* Back to a pod to launch the e2e test

* Create test as a hook to be able to delete it

* Fix issues with the chart installation

* Add the uninstall of the e2e helm chart

* Move selenium to test and install and uninstall in CI

* Add wait and error handling to the ci

* Separate clean up in case of errors

* Fix a continue on error in the e2e chart

* Change tries to 30 to wait up to 5 minutes for apps to be healthy

* Add documentation for the test e2e in GETTING_STARTED.md

* Change marinera-e2e image to 0.0.2-PRE-3

* Update e2e image to 0.0.2 and restablish datasource-checker

* Add changes in the ci to get the number of components from the values

* try the old image

* Add random string to name

allows testrerun in case of failure

* quotes are dumb here...

* and it needs to be lowercase

* correct grafana and temorary no cleanup

* Update values.yaml

* Update values.yaml

* disable the services

* Update values.yaml

* fix grafana url

* remove mttest prefix

Co-authored-by: Stefan Wiedemann <wistefan@googlemail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -70,3 +70,69 @@ jobs:
           cd fiware-platform/
           # render app of apps and apply it
           helm template . | oc -n labs-ci-cd apply -f -
+          cd ..
+
+      - name: Check if all apps are healthy
+        run: |
+          # bool to check if the apps are healthy
+          healthy=0
+          # counter to set a number of tries
+          try=0
+          tries=30
+          # get the list of apps in the namespace 
+          componentsInstalled=$(grep "enabled: true" fiware-platform/values.yaml -c)
+          # check if the condition is met
+          while [ $healthy == 0 ] && [ $try -lt $tries ]
+          do
+            apps=$(oc get applications.argoproj.io --no-headers -n labs-ci-cd -l destination-namespace=${{ steps.branch-name.outputs.current_branch }} | awk '{ print $3 }')
+            healthyapps=0
+            for app in $apps
+            do
+              if [ $app != "Healthy" ]
+              then
+                echo "Trying again in 10 seconds"
+                sleep 10
+                try=$(( try + 1 ))
+                break
+              elif [ $app == "Healthy" ]
+              then  
+                healthyapps=$(( healthyapps + 1 ))
+              fi
+              if [ $healthyapps == $componentsInstalled ]
+              then
+                healthy=1
+              fi
+            done
+          done
+
+          if [ $try -eq $tries ]
+          then
+            echo "ERROR: Tried too many times"
+            exit 1
+          fi
+
+      - name: Deploy the helm charts for the e2e
+        run: |
+          # go to selenium-grid directory
+          cd tests/selenium-grid
+          # install selenium-grid
+          helm install --wait selenium . -n ${{ steps.branch-name.outputs.current_branch }}
+          # go to the e2e-test directory
+          cd ../e2e-test
+          # replace the default destination namespace(demo) with the branch namespace in the Grafana URL
+          sed -i 's/demo/${{ steps.branch-name.outputs.current_branch }}/' values.yaml 
+          # install the helm chart
+          helm install e2e . -n ${{ steps.branch-name.outputs.current_branch }}
+          
+      - name: Uninstall marinera-e2e helm chart
+        if: always()
+        run: |
+          # uninstall the e2e helm chart
+          helm uninstall e2e -n ${{ steps.branch-name.outputs.current_branch }}
+
+      - name: Uninstall selenium-grid helm chart
+        if: always()
+        run: |
+          # uninstall the selenium-grid helm chart
+          helm uninstall selenium -n ${{ steps.branch-name.outputs.current_branch }}
+
